// <auto-generated />
using System;
using AAO_AdminPanel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AAO_AdminPanel.Migrations.MySQLDb
{
    [DbContext(typeof(MySQLDbContext))]
    [Migration("20211119100427_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("AAO_AdminPanel.Models.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddressLine")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AddressID");

                    b.HasIndex("UserID");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Availability", b =>
                {
                    b.Property<int>("AvailabilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("AvailabilityID");

                    b.HasIndex("DriverID");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("varchar(45)");

                    b.HasKey("CityID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Country", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasColumnType("varchar(255)");

                    b.HasKey("CountryID");

                    b.HasIndex("CityID")
                        .IsUnique();

                    b.ToTable("Country");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("DepartmentID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Driver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("StartLocationID")
                        .HasColumnType("int");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("DriverID");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.DriverLicense", b =>
                {
                    b.Property<int>("LicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("DriverID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.HasKey("LicenseID");

                    b.ToTable("DriverLicense");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.License", b =>
                {
                    b.Property<int>("LicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("LicenseName")
                        .HasColumnType("text");

                    b.HasKey("LicenseID");

                    b.ToTable("License");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Request", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("DriverID");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.StartLocation", b =>
                {
                    b.Property<int>("StartLocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.HasKey("StartLocationID");

                    b.ToTable("StartLocation");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("StatusID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Traffic", b =>
                {
                    b.Property<int>("TrafficID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("StartCountryID")
                        .HasColumnType("int");

                    b.Property<int>("StopCountryID")
                        .HasColumnType("int");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("TrafficID");

                    b.ToTable("Traffic");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.TrafficType", b =>
                {
                    b.Property<int>("TypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("TypeID");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Trip", b =>
                {
                    b.Property<int>("TripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContactID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionOfTrip")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateAndTime")
                        .HasColumnType("datetime");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StopDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TrafficID")
                        .HasColumnType("int");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.HasKey("TripID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Trip");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.TripHasDriver", b =>
                {
                    b.Property<int>("DriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("TripID")
                        .HasColumnType("int");

                    b.HasKey("DriverID");

                    b.ToTable("TripHasDriver");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Firstname")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Lastname")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(64)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(45)");

                    b.HasKey("UserID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("RoleID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Address", b =>
                {
                    b.HasOne("AAO_AdminPanel.Models.User", "User")
                        .WithMany("Addresses")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Availability", b =>
                {
                    b.HasOne("AAO_AdminPanel.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverID");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Country", b =>
                {
                    b.HasOne("AAO_AdminPanel.Models.City", null)
                        .WithOne("Country")
                        .HasForeignKey("AAO_AdminPanel.Models.Country", "CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Trip", b =>
                {
                    b.HasOne("AAO_AdminPanel.Models.Department", null)
                        .WithMany("Trips")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.User", b =>
                {
                    b.HasOne("AAO_AdminPanel.Models.Department", "Department")
                        .WithMany("UserID")
                        .HasForeignKey("DepartmentID");

                    b.HasOne("AAO_AdminPanel.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.City", b =>
                {
                    b.Navigation("Country");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Department", b =>
                {
                    b.Navigation("Trips");

                    b.Navigation("UserID");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AAO_AdminPanel.Models.User", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
